import {
  mdiAccessPoint,
  mdiAirConditioner,
  mdiAlarmBell,
  mdiAlarmLightOutline,
  mdiAlertOutline,
  mdiAlertRhombusOutline,
  mdiArrowBottomLeft,
  mdiArrowBottomRight,
  mdiArrowDown,
  mdiArrowLeft,
  mdiArrowLeftRight,
  mdiArrowRight,
  mdiArrowTopLeft,
  mdiArrowTopRight,
  mdiArrowUp,
  mdiArrowUpDown,
  mdiBathtubOutline,
  mdiBedOutline,
  mdiBellOutline,
  mdiCctv,
  mdiChevronDoubleLeft,
  mdiChevronDoubleRight,
  mdiChevronDown,
  mdiChevronLeft,
  mdiChevronRight,
  mdiChevronUp,
  mdiCompass,
  mdiCompassOutline,
  mdiCrosshairsGps,
  mdiDoor,
  mdiDoorClosed,
  mdiDoorOpen,
  mdiElevatorPassenger,
  mdiEvStation,
  mdiFan,
  mdiFaucet,
  mdiFoodForkDrink,
  mdiFridgeOutline,
  mdiGarageVariant,
  mdiHomeFloor0,
  mdiHomeFloor1,
  mdiHomeOutline,
  mdiHumanFemale,
  mdiHumanMale,
  mdiLightbulbOutline,
  mdiLockOpenOutline,
  mdiLockOutline,
  mdiMapMarkerOutline,
  mdiMotionSensor,
  mdiNavigation,
  mdiNavigationVariantOutline,
  mdiParking,
  mdiPool,
  mdiPowerPlugOutline,
  mdiRadioTower,
  mdiSecurity,
  mdiShieldHomeOutline,
  mdiShower,
  mdiSilverwareForkKnife,
  mdiSmokeDetectorVariant,
  mdiSofaOutline,
  mdiStairs,
  mdiStove,
  mdiSunClock,
  mdiTableChair,
  mdiThermometer,
  mdiToilet,
  mdiWaterBoiler,
  mdiWeatherNight,
  mdiWeatherPartlyCloudy,
  mdiWeatherSunny,
  mdiWheelchairAccessibility,
  mdiWifi,
  mdiWindowClosedVariant,
  mdiWindowOpenVariant,
  mdiWashingMachine,
} from '@mdi/js';

const iconDefs = [
  // Alarm / security
  { id: 'alarm-bell', pathData: mdiAlarmBell, label: 'Alarm Bell', group: 'Alarm' },
  { id: 'bell', pathData: mdiBellOutline, label: 'Bell', group: 'Alarm' },
  { id: 'alarm-light', pathData: mdiAlarmLightOutline, label: 'Alarm Light', group: 'Alarm' },
  { id: 'warning', pathData: mdiAlertOutline, label: 'Warning', group: 'Alarm' },
  { id: 'warning-rhombus', pathData: mdiAlertRhombusOutline, label: 'Warning Triangle', group: 'Alarm' },
  { id: 'smoke', pathData: mdiSmokeDetectorVariant, label: 'Smoke Detector', group: 'Alarm' },
  { id: 'lock', pathData: mdiLockOutline, label: 'Lock', group: 'Alarm' },
  { id: 'unlock', pathData: mdiLockOpenOutline, label: 'Unlock', group: 'Alarm' },
  { id: 'cctv', pathData: mdiCctv, label: 'CCTV', group: 'Alarm' },
  { id: 'security', pathData: mdiSecurity, label: 'Security', group: 'Alarm' },
  { id: 'shield-home', pathData: mdiShieldHomeOutline, label: 'Shield Home', group: 'Alarm' },

  // Area / building
  { id: 'home', pathData: mdiHomeOutline, label: 'Home', group: 'Area' },
  { id: 'home-floor0', pathData: mdiHomeFloor0, label: 'Ground Floor', group: 'Area' },
  { id: 'home-floor1', pathData: mdiHomeFloor1, label: 'First Floor', group: 'Area' },
  { id: 'window-closed', pathData: mdiWindowClosedVariant, label: 'Window Closed', group: 'Area' },
  { id: 'window-open', pathData: mdiWindowOpenVariant, label: 'Window Open', group: 'Area' },
  { id: 'door', pathData: mdiDoor, label: 'Door', group: 'Area' },
  { id: 'door-closed', pathData: mdiDoorClosed, label: 'Door Closed', group: 'Area' },
  { id: 'door-open', pathData: mdiDoorOpen, label: 'Door Open', group: 'Area' },
  { id: 'stairs', pathData: mdiStairs, label: 'Stairs', group: 'Area' },
  { id: 'elevator', pathData: mdiElevatorPassenger, label: 'Elevator', group: 'Area' },
  { id: 'garage', pathData: mdiGarageVariant, label: 'Garage', group: 'Area' },
  { id: 'marker', pathData: mdiMapMarkerOutline, label: 'Map Marker', group: 'Area' },
  { id: 'parking', pathData: mdiParking, label: 'Parking', group: 'Area' },

  // Facility / accessibility
  { id: 'male', pathData: mdiHumanMale, label: 'Male', group: 'Facility' },
  { id: 'female', pathData: mdiHumanFemale, label: 'Female', group: 'Facility' },
  { id: 'wheelchair', pathData: mdiWheelchairAccessibility, label: 'Accessible', group: 'Facility' },
  { id: 'toilet', pathData: mdiToilet, label: 'Toilet', group: 'Facility' },
  { id: 'bed', pathData: mdiBedOutline, label: 'Bedroom', group: 'Facility' },
  { id: 'shower', pathData: mdiShower, label: 'Shower', group: 'Facility' },
  { id: 'bathtub', pathData: mdiBathtubOutline, label: 'Bathtub', group: 'Facility' },
  { id: 'sofa', pathData: mdiSofaOutline, label: 'Living Room', group: 'Facility' },
  { id: 'table', pathData: mdiTableChair, label: 'Table', group: 'Facility' },
  { id: 'faucet', pathData: mdiFaucet, label: 'Faucet', group: 'Facility' },
  { id: 'stove', pathData: mdiStove, label: 'Stove', group: 'Facility' },
  { id: 'washer', pathData: mdiWashingMachine, label: 'Washing Machine', group: 'Facility' },
  { id: 'fridge', pathData: mdiFridgeOutline, label: 'Fridge', group: 'Facility' },

  // Utilities
  { id: 'lightbulb', pathData: mdiLightbulbOutline, label: 'Light', group: 'Utility' },
  { id: 'plug', pathData: mdiPowerPlugOutline, label: 'Power', group: 'Utility' },
  { id: 'wifi', pathData: mdiWifi, label: 'WiFi', group: 'Utility' },
  { id: 'access-point', pathData: mdiAccessPoint, label: 'Access Point', group: 'Utility' },
  { id: 'radio', pathData: mdiRadioTower, label: 'Radio', group: 'Utility' },
  { id: 'motion', pathData: mdiMotionSensor, label: 'Motion Sensor', group: 'Utility' },
  { id: 'ac', pathData: mdiAirConditioner, label: 'Air conditioner', group: 'Utility' },
  { id: 'fan', pathData: mdiFan, label: 'Fan', group: 'Utility' },
  { id: 'boiler', pathData: mdiWaterBoiler, label: 'Boiler', group: 'Utility' },
  { id: 'thermometer', pathData: mdiThermometer, label: 'Thermometer', group: 'Utility' },
  { id: 'ev', pathData: mdiEvStation, label: 'EV station', group: 'Utility' },

  // Arrows
  { id: 'arrow-left', pathData: mdiArrowLeft, label: 'Arrow left', group: 'Arrows' },
  { id: 'arrow-right', pathData: mdiArrowRight, label: 'Arrow right', group: 'Arrows' },
  { id: 'arrow-up', pathData: mdiArrowUp, label: 'Arrow up', group: 'Arrows' },
  { id: 'arrow-down', pathData: mdiArrowDown, label: 'Arrow down', group: 'Arrows' },
  { id: 'arrow-tl', pathData: mdiArrowTopLeft, label: 'Arrow top left', group: 'Arrows' },
  { id: 'arrow-tr', pathData: mdiArrowTopRight, label: 'Arrow top right', group: 'Arrows' },
  { id: 'arrow-bl', pathData: mdiArrowBottomLeft, label: 'Arrow bottom left', group: 'Arrows' },
  { id: 'arrow-br', pathData: mdiArrowBottomRight, label: 'Arrow bottom right', group: 'Arrows' },
  { id: 'arrow-lr', pathData: mdiArrowLeftRight, label: 'Arrow left-right', group: 'Arrows' },
  { id: 'arrow-ud', pathData: mdiArrowUpDown, label: 'Arrow up-down', group: 'Arrows' },
  { id: 'chev-left', pathData: mdiChevronLeft, label: 'Chevron left', group: 'Arrows' },
  { id: 'chev-right', pathData: mdiChevronRight, label: 'Chevron right', group: 'Arrows' },
  { id: 'chev-up', pathData: mdiChevronUp, label: 'Chevron up', group: 'Arrows' },
  { id: 'chev-down', pathData: mdiChevronDown, label: 'Chevron down', group: 'Arrows' },
  { id: 'chev-double-left', pathData: mdiChevronDoubleLeft, label: 'Double left', group: 'Arrows' },
  { id: 'chev-double-right', pathData: mdiChevronDoubleRight, label: 'Double right', group: 'Arrows' },

  // Astro / orientation
  { id: 'compass', pathData: mdiCompass, label: 'Compass', group: 'Astro' },
  { id: 'compass-outline', pathData: mdiCompassOutline, label: 'Compass outline', group: 'Astro' },
  { id: 'navigation', pathData: mdiNavigation, label: 'Navigation', group: 'Astro' },
  { id: 'navigation-outline', pathData: mdiNavigationVariantOutline, label: 'Navigation outline', group: 'Astro' },
  { id: 'crosshair-gps', pathData: mdiCrosshairsGps, label: 'GPS', group: 'Astro' },
  { id: 'sun', pathData: mdiWeatherSunny, label: 'Sun', group: 'Astro' },
  { id: 'night', pathData: mdiWeatherNight, label: 'Night', group: 'Astro' },
  { id: 'partly-cloudy', pathData: mdiWeatherPartlyCloudy, label: 'Partly cloudy', group: 'Astro' },
  { id: 'sun-clock', pathData: mdiSunClock, label: 'Sun clock', group: 'Astro' },

  // More facility icons
  { id: 'food', pathData: mdiFoodForkDrink, label: 'Dining', group: 'Facility' },
  { id: 'cutlery', pathData: mdiSilverwareForkKnife, label: 'Cutlery', group: 'Facility' },
  { id: 'pool', pathData: mdiPool, label: 'Pool', group: 'Facility' },
];

export const JUNG_ICON_GROUPS = ['All', 'Alarm', 'Area', 'Facility', 'Utility', 'Arrows', 'Astro'];

export const JUNG_ICONS = iconDefs;

