import { Router } from "express";
import authRoutes from "./authRoutes.js";
import userRoutes from "./userRoutes.js";
import rangeRoutes from "./rangeRoutes.js";
import productRoutes from "./productRoutes.js";
import collectionRoutes from "./collectionRoutes.js";
import projectRoutes from "./projectRoutes.js";
import canvasRoutes from "./canvasRoutes.js";
import pdfRoutes from "./pdfRoutes.js";
import adminDashboardRoutes from "./adminDashboardRoutes.js";
import categoryRoutes from "./categoryRoutes.js";
import solutionRoutes from "./solutionRoutes.js";
import solutionDetailRoutes from "./solutionDetailRoutes.js";
import pdfMaterialRoutes from "./pdfMaterialRoutes.js";
import cookiePolicyRoutes from "./cookiePolicyRoutes.js";
import newsletterRoutes from "./newsletterRoutes.js";
import iconCategoryRoutes from "./iconCategoryRoutes.js";
import iconRoutes from "./iconRoutes.js";

const router = Router();

router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/ranges", rangeRoutes);
router.use("/products", productRoutes);
router.use("/collections", collectionRoutes);
router.use("/projects", projectRoutes);
router.use("/canvas", canvasRoutes);
router.use("/pdf", pdfRoutes);
router.use("/admin/dashboard", adminDashboardRoutes);
router.use("/categories", categoryRoutes);
router.use("/solutions", solutionRoutes);
router.use("/solution-details", solutionDetailRoutes);
router.use("/pdf-materials", pdfMaterialRoutes);
router.use("/cookie-policy", cookiePolicyRoutes);
router.use("/newsletter", newsletterRoutes);
router.use("/icon-categories", iconCategoryRoutes);
router.use("/icons", iconRoutes);

export default router;
